
---
- hosts: web
  remote_user: ansible
  sudo: yes
  gather_facts: yes
  
  vars:
    path: "/opt/"
    envpath: "export JAVA_HOME='/opt/jdk1.8.0_211'\n export PATH=$JAVA_HOME/bin:$PATH\n\n export CATALINA_HOME='/opt/apache-tomcat-8.5.41'\n export PATH=$CATALINA_HOME/bin:$PATH"
    urls:
      - https://download.oracle.com/otn/java/jdk/8u211-b12/478a62b7d4e34b78b671c754eaaf38ab/jdk-8u211-linux-x64.tar.gz?AuthParam=1560177419_5ceafd3f4b32b17c350f6bef8ab95b8f  
      - http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.41/bin/apache-tomcat-8.5.41.tar.gz
    files:
      - /opt/jdk-8u211-linux-x64.tar.gz
      - /opt/apache-tomcat-8.5.41.tar.gz

  tasks: 
  - name: download pkgs
    get_url:
      url: "{{ item }}"
      dest: "{{ path }}"
    with_items: "{{ urls }}"
  
  - name: extract pkgs
    unarchive:
      src: "{{ item }}"
      dest: "{{ path }}"
    with_items: "{{ files }}"

  - name: set env paths
    copy:
      content: "{{ envpath }}"
      dest: /home/ansible/.profile
    when: ansible_distribution=="Ubuntu"

  - name: set env paths
    copy:
      content: "{{ envpath }}"
      dest: /home/ansible/.bashrc
    when: ansible_distribution=="CentOS"
 
  - name: update psths
    raw: source .profile
    when: ansible_distribution=="Ubuntu"

  - name: update psths
    shell: source .bashrc
    when: ansible_distribution=="CentOS"

  - name: startup
    command: /opt/apache-tomcat-8.5.41/bin/startup.sh
    sudo_user: ansible
        












