---
# tasks file for wordpress
- name: download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no

- name: extract
  unarchive:  
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    copy: no

- name: Update default Apache site
  sudo: yes
  lineinfile:
    dest: /etc/apache2/sites-enabled/000-default.conf
    regexp: "(.)+DocumentRoot /var/www/html"
    line: "DocumentRoot /var/www/wordpress"
  when: ansible_distribution=="Ubuntu"
  notify:
    - restart apache2

- name: Copy sample config files
  raw: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php 
  when: ansible_distribution=="Ubuntu"
   
- name: Update WordPress config file
  lineinfile:
    dest: /var/www/wordpress/wp-config.php
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}        
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}        
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}
  when: ansible_distribution=="Ubuntu"
    
  notify:
    - restart apache2

